# Generated by Django 3.2.8 on 2022-05-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20220525_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='description',
            new_name='descripcion',
        ),
    ]
